"""Generated artifact model."""

from pydantic import BaseModel, Field
from datetime import datetime


class GeneratedArtifact(BaseModel):
    """Artifact generated by an AI agent."""

    content: str = Field(..., description="The generated content")
    file_type: str = Field(..., description="Type of file (e.g., 'py', 'md', 'txt')")
    agent_name: str = Field(..., description="Name of the agent that generated this")
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    metadata: dict = Field(default_factory=dict, description="Additional metadata")
